// <auto-generated />
using System;
using DrillRoad.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrillRoad.Database.Migrations
{
    [DbContext(typeof(RoadMapDbContext))]
    [Migration("20240923230011_addRealRelation")]
    partial class addRealRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("main")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrillRoad.Contracts.Account.UserDrillIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AdditionalUserInfoIdId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalUserInfoIdId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactRowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PictureRepoPatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactRowId");

                    b.ToTable("AdditionalUserInfoRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.AddressRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .HasColumnType("text");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.ContactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("ContactRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Media.VideoRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FightActionRowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PositionRowId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransitionRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoRepoPatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FightActionRowId");

                    b.HasIndex("PositionRowId");

                    b.HasIndex("TransitionRowId");

                    b.ToTable("VideoRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.FightActionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AdditionalUserInfoRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FightActionRowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StartingPositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalUserInfoRowId");

                    b.HasIndex("FightActionRowId");

                    b.HasIndex("StartingPositionId");

                    b.ToTable("FightActionRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.PositionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdditionalUserInfoRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalUserInfoRowId");

                    b.ToTable("PositionRow", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.TransitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdditionalUserInfoRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FinalPositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitialPositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PositionRowId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransitionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalUserInfoRowId");

                    b.HasIndex("FinalPositionId");

                    b.HasIndex("InitialPositionId");

                    b.HasIndex("PositionRowId");

                    b.ToTable("TransitionRow", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "main");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "main");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Account.UserDrillIdentity", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", "AdditionalUserInfoId")
                        .WithMany("trainers")
                        .HasForeignKey("AdditionalUserInfoIdId");

                    b.Navigation("AdditionalUserInfoId");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.ContactRow", "ContactRow")
                        .WithMany()
                        .HasForeignKey("ContactRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactRow");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.ContactRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.AddressRow", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Media.VideoRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.FightActionRow", null)
                        .WithMany("TutorialVideos")
                        .HasForeignKey("FightActionRowId");

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.PositionRow", null)
                        .WithMany("TutorialVideos")
                        .HasForeignKey("PositionRowId");

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.TransitionRow", null)
                        .WithMany("TutorialVideos")
                        .HasForeignKey("TransitionRowId");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.FightActionRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", null)
                        .WithMany("fightActions")
                        .HasForeignKey("AdditionalUserInfoRowId");

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.FightActionRow", null)
                        .WithMany("PossibleOpponentActions")
                        .HasForeignKey("FightActionRowId");

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.PositionRow", "StartingPosition")
                        .WithMany("PossibleActions")
                        .HasForeignKey("StartingPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StartingPosition");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.PositionRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", null)
                        .WithMany("positions")
                        .HasForeignKey("AdditionalUserInfoRowId");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.TransitionRow", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", null)
                        .WithMany("transactions")
                        .HasForeignKey("AdditionalUserInfoRowId");

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.PositionRow", "FinalPosition")
                        .WithMany()
                        .HasForeignKey("FinalPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.PositionRow", "InitialPosition")
                        .WithMany()
                        .HasForeignKey("InitialPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrillRoad.Contracts.Tables.Techniques.PositionRow", null)
                        .WithMany("PossibleTransitions")
                        .HasForeignKey("PositionRowId");

                    b.Navigation("FinalPosition");

                    b.Navigation("InitialPosition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Account.UserDrillIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Account.UserDrillIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrillRoad.Contracts.Account.UserDrillIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DrillRoad.Contracts.Account.UserDrillIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Account.AdditionalUserInfoRow", b =>
                {
                    b.Navigation("fightActions");

                    b.Navigation("positions");

                    b.Navigation("trainers");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.FightActionRow", b =>
                {
                    b.Navigation("PossibleOpponentActions");

                    b.Navigation("TutorialVideos");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.PositionRow", b =>
                {
                    b.Navigation("PossibleActions");

                    b.Navigation("PossibleTransitions");

                    b.Navigation("TutorialVideos");
                });

            modelBuilder.Entity("DrillRoad.Contracts.Tables.Techniques.TransitionRow", b =>
                {
                    b.Navigation("TutorialVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
